### ISSUE TITLE
`fetch_teas` fails with ValueError when trying to create a driver object

### ISSUE THREAD

**Issue by GeorgySk** [GeorgySk/teashop#2]
The error:
```
>>> from teashop import fetch_teas
>>> teas = fetch_teas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/georgy/teashop/teashop/teashop.py", line 75, in fetch_teas
    driver = _create_driver()
  File "/home/georgy/teashop/teashop/teashop.py", line 17, in _create_driver
    driver_path = ChromeDriverManager(path='.').install()
  File "/home/georgy/miniconda3/envs/teashop/lib/python3.10/site-packages/webdriver_manager/chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
  File "/home/georgy/miniconda3/envs/teashop/lib/python3.10/site-packages/webdriver_manager/core/manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
  File "/home/georgy/miniconda3/envs/teashop/lib/python3.10/site-packages/webdriver_manager/core/download_manager.py", line 28, in download_file
    response = self._http_client.get(url)
  File "/home/georgy/miniconda3/envs/teashop/lib/python3.10/site-packages/webdriver_manager/core/http.py", line 33, in get
    self.validate_response(resp)
  File "/home/georgy/miniconda3/envs/teashop/lib/python3.10/site-packages/webdriver_manager/core/http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/119.0.6045/chromedriver_linux64.zip
```

**Comment by GeorgySk** [comment]
Resolved with https://github.com/GeorgySk/teashop/pull/4
